// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Airdrop Progress Animation",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Airdrop Progress Animation",
            targets: ["AppModule"],
            bundleIdentifier: "Mert-Tecimen.Airdrop-Progress-Animation",
            teamIdentifier: "R2MF39ASQT",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .tv),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)